---
role_name_check: 0
dependency:
  name: galaxy
driver:
  name: default
  options:
    managed: true
platforms:
  - name: ec2-rockylinux9
    type: ec2
    image: ami-01bd836275f79352c
    region: us-east-2
    vpc_id: vpc-0eb9fd1391f4207ec
    vpc_subnet_id: subnet-0aa189c0d6fc53923
    instance_type: t3.micro
    ssh_user: molecule_runner
    hostvars:
      test_hostvar: test
  - name: ec2-unbuntu2204
    type: ec2
    image: ami-0cb91c7de36eed2cb
    region: us-east-2
    vpc_id: vpc-0eb9fd1391f4207ec
    vpc_subnet_id: subnet-0aa189c0d6fc53923
    instance_type: t3.micro
    ssh_user: molecule_runner
    hostvars:
      test_hostvar: test
provisioner:
  name: ansible
  log: True
  playbooks:
    create: ../resources/create.yml
    prepare: ../resources/prepare.yml
    converge: ../resources/converge.yml
    side_effect: ../resourcs/side_effect.yml
    verify: ../resources/verify.yml
    cleanup: ../resources/cleanup.yml
    destroy: ../resources/destroy.yml
  config_options:
    defaults:
      gathering: explicit
      playbook_vars_root: top
      verbosity: ${ANSIBLE_VERBOSITY:-0}
  env:
    ARA_API_CLIENT: ${ARA_API_CLIENT:-'http'}
    ARA_API_SERVER: ${ARA_API_SERVER:-'http://localhost:8000'}
    ARA_DEFAULT_LABELS: ${ARA_DEFAULT_LABELS:-'testing,molecule'}
    # To use Ara with molecule:
    #  export the ANSIBLE_CALLBACK_PLUGINS env var with the output of 'python3 -m ara.setup.callback_plugins'
    ANSIBLE_CALLBACK_PLUGINS: ${ANSIBLE_CALLBACK_PLUGINS}
scenario:
  create_sequence:
    - dependency
    - create
  check_sequence:
    - dependency
    - cleanup
    - destroy
    - create
    - prepare
    - converge
    - check
    - destroy
  converge_sequence:
    - dependency
    - create
    - prepare
    - converge
  destroy_sequence:
    - dependency
    - cleanup
    - destroy
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy
verifier:
  name: ansible
  enabled: true

