
FROM {{ __docker_platform_definition.image }}

{% for __run_command in __docker_platform_definition.exec_systemd_build_commands %}
RUN {{ __run_command }}
{% endfor %}

ENTRYPOINT ["{{ __docker_platform_definition.exec_systemd_path | default(docker_platform_container_defaults.exec_systemd_path) }}"]

