---
# Set up for executing a local project

- name: Build collection path
  block:
    - name: Load collection config file
      ansible.builtin.include_vars:
        file: "{{ prepare_controller_project_dir }}/galaxy.yml"
        name: __prepare_controller_project_meta

    - name: Collection information loaded
      ansible.builtin.assert:
        that:
          - __prepare_controller_project_meta.namespace is defined
          - __prepare_controller_project_meta.namespace is truthy
          - __prepare_controller_project_meta.name is defined
          - __prepare_controller_project_meta.name is truthy
          - __prepare_controller_project_meta.version is defined
          - __prepare_controller_project_meta.name is truthy
        fail_msg: Collection configuration data missing!
        success_msg: Collection Galaxy configuration passed!
  rescue:
    - name: Configuration error
      ansible.builtin.fail:
        msg: Error loading collection Galaxy information! This molecule configuration is meant to be run from the root of your project directory!


## NOTE: Molecule appears to automatically install collections in the default user location on run -- though knowing the details of this would be nice
#- name: Link project directory
#  block:
#    - name: Generate collection path
#      ansible.builtin.set_fact:
#        __prepare_controller_collection_internal_dir: "{{ prepare_controller_collection_dir }}/ansible_collections/{{ __prepare_controller_project_meta.namespace }}"
#    - name: Collection namespace directory exists
#      ansible.builtin.file:
#        path: "{{ __prepare_controller_collection_internal_dir }}"
#        state: directory
#        mode: 0755
#
#    - name: Project is linked
#      ansible.builtin.file:
#        source: "{{ prepare_controller_project_dir }}"
#        dest: "{{ __prepare_controller_collection_internal_dir }}/{{ __prepare_controller_project_meta.name }}"
#        state: link

