---
# tasks file for prepare_controller

- name: Project directory is
  ansible.builtin.debug:
    var: prepare_controller_project_dir

- name: Verify project type
  ansible.builtin.assert:
    that:
      - prepare_controller_project_type is in ['role', 'collection', 'monolith']
    fail_msg: Unsupported project type specified!
    success_msg: Project type is supported

- name: Configure controller for role project type
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/role.yml"
  when: prepare_controller_project_type == 'role'

- name: Configure controller for collection project type
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/collection.yml"
  when: prepare_controller_project_type == 'collection'

- name: Configure controller for monolith project type
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/monolith.yml"
  when: prepare_controller_project_type == 'monolith'

