---
- name: Create
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Create platform
      ansible.builtin.include_role:
        name: syndr.molecule.platform
      vars:
        platform_name: "{{ item.name }}"
        platform_state: present
        platform_type: "{{ item.type }}"
        platform_molecule_cfg: "{{ item }}"
      loop: "{{ molecule_yml.platforms }}"
      loop_control:
        label: item.name

# We want to avoid errors like "Failed to create temporary directory"
- name: Validate that inventory was refreshed
  hosts: molecule
  gather_facts: false
  tasks:
    - name: Check uname
      ansible.builtin.raw: uname -a
      register: result
      changed_when: false

    - name: Display uname info
      ansible.builtin.debug:
        msg: "{{ result.stdout }}"

    - name: Load system facts
      ansible.builtin.setup:
        filter:
          - ansible_service_mgr

    - name: Check on Systemd
      block:
        - name: Wait for systemd to complete initialization.
          ansible.builtin.command: systemctl is-system-running
          register: systemctl_status
          until: >
            'running' in systemctl_status.stdout or
            'degraded' in systemctl_status.stdout
          retries: 30
          delay: 5
          changed_when: false
          failed_when: systemctl_status.rc > 1

        - name: Check systemd status
          ansible.builtin.assert:
            that:
              - systemctl_status.stdout == 'running'
            fail_msg: Systemd-enabled container does not have a healthy Systemd!
            success_msg: Systemd is running
      when: ansible_service_mgr == 'systemd'

