---
role_name_check: 0
dependency:
  name: galaxy
driver:
  name: default
  options:
    managed: true
    login_cmd_template: 'docker exec -ti {instance} bash'
platforms:
  - name: docker-rockylinux9
    type: docker
    image: geerlingguy/docker-rockylinux9-ansible:latest
    systemd: True
    modify_image: False
    privileged: False
    hostvars: {}
  - name: docker-fedora39
    type: docker
    image: geerlingguy/docker-fedora39-ansible:latest
    systemd: True
    modify_image: False
    privileged: False
    hostvars: {}
  - name: docker-ubuntu2204
    type: docker
    image: geerlingguy/docker-ubuntu2204-ansible:latest
    systemd: True
    modify_image: False
    privileged: False
    hostvars: {}
provisioner:
  name: ansible
  log: True
  playbooks:
    prepare: prepare.yml
    converge: converge.yml
    side_effect: side_effect.yml
    verify: verify.yml
    cleanup: cleanup.yml
  config_options:
    defaults:
      gathering: explicit
      verbosity: ${ANSIBLE_VERBOSITY:-0}
scenario:
  create_sequence:
    - dependency
    - create
    - prepare
  check_sequence:
    - dependency
    - cleanup
    - destroy
    - create
    - prepare
    - converge
    - check
    - destroy
  converge_sequence:
    - dependency
    - create
    - prepare
    - converge
  destroy_sequence:
    - dependency
    - cleanup
    - destroy
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy
verifier:
  name: ansible
  enabled: true

