---
# tasks file for platform

- name: Platform is provisioned
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/provision.yml"
  when: platform_state == 'present'

- name: Platform is destroyed
  ansible.builtin.include_tasks: "{ role_path }}/tasks/destroy.yml"
  when: platform_state == 'absent'

