---
# Verify that the role being tested has done what it's supposed to

- name: Verify
  hosts: molecule
  tasks:
    - name: Load local host facts
      ansible.builtin.setup:
        gather_subset:
          - '!all'
          - '!min'
          - local

    - name: Load test data (example)
      ansible.builtin.set_fact:
        test_prepare_fact: "{{ ansible_local.molecule.test_prepare_fact }}"

    - name: Add your verification tasks here
      ansible.builtin.debug:
        msg: "IE: For a 'users' role, check that the test user exists"

