---
# Automagically deturmine what type of Ansible project this is

- name: Check for role meta configuration
  ansible.builtin.stat:
    path: "{{ init_project_dir }}/meta/main.yml"
  register: __init_rolepath_stat

- name: Check for collection Galaxy configuration
  ansible.builtin.stat:
    path: "{{ init_project_dir }}/galaxy.yml"
  register: __init_collectionpath_stat

- name: Check for monolith
  block:
    - name: Check for top-level roles directory
      ansible.builtin.stat:
        path: "{{ init_project_dir }}/roles"
      register: __init_monoroles_stat

    - name: Check for top-level playbooks directory
      ansible.builtin.stat:
        path: "{{ init_project_dir }}/playbooks"
      register: __init_monoplaybooks_stat

    - name: Monolith repository detected
      ansible.builtin.set_fact:
        __init_monolith: true
      when:
        - __init_monoroles_stat.stat.exists is true
        - __init_monoplaybooks_stat.stat.exists is true

- name: Perform convergence dance
  block:
    - name: Detect crossed streams
      ansible.builtin.assert:
        that: __init_rolepath_stat.stat.exists is true and
            __init_collectionpath_stat.stat.exists is false and
            __init_monolith is false or
            __init_collectionpath_stat.stat.exists is true or
            __init_monolith is true and
            __init_rolepath_stat.stat.exists is false
        success_msg: Known repository format detected!
        fail_msg: No known repository type detected. 😵

    - name: Role repository detected
      ansible.builtin.set_fact:
        init_project_type: role
      when:
          - __init_rolepath_stat.stat.exists is true
          - __init_collectionpath_stat.stat.exists is false
          - __init_monolith is false

    - name: Collection repository detected
      ansible.builtin.set_fact:
        init_project_type: collection
      when: __init_collectionpath_stat.stat.exists is true

    - name: Monolith repository detected
      ansible.builtin.set_fact:
        init_project_type: monolith
      when:
        - __init_monolith is true
        - __init_rolepath_stat.stat.exists is false

- name: Autodetection succeeded
  ansible.builtin.assert:
    that:
      - init_project_type != 'auto'
    fail_msg: Autodetection of repository type failed!


