---
# Automagically deturmine what type of Ansible project this is

- name: Check for role meta configuration
  ansible.builtin.stat:
    path: "{{ init_project_dir }}/meta/main.yml"
  register: init__rolepath_stat

- name: Check for collection Galaxy configuration
  ansible.builtin.stat:
    path: "{{ init_project_dir }}/galaxy.yml"
  register: init__collectionpath_stat

- name: Check for monolith
  block:
    - name: Check for top-level roles directory
      ansible.builtin.stat:
        path: "{{ init_project_dir }}/roles"
      register: init__monoroles_stat

    - name: Check for top-level playbooks directory
      ansible.builtin.stat:
        path: "{{ init_project_dir }}/playbooks"
      register: init__monoplaybooks_stat

    - name: Monolith repository detected
      ansible.builtin.set_fact:
        init__monolith: true
      when:
        - init__monoroles_stat.stat.exists is true
        - init__monoplaybooks_stat.stat.exists is true

- name: Perform convergence dance
  block:
    - name: Detect crossed streams
      ansible.builtin.assert:
        that: init__rolepath_stat.stat.exists is true and
            init__collectionpath_stat.stat.exists is false and
            init__monolith is false or
            init__collectionpath_stat.stat.exists is true or
            init__monolith is true and
            init__rolepath_stat.stat.exists is false
        success_msg: Known repository format detected!
        fail_msg: No known repository type detected. 😵

    - name: Role repository detected
      ansible.builtin.set_fact:
        init_project_type: role
      when:
          - init__rolepath_stat.stat.exists is true
          - init__collectionpath_stat.stat.exists is false
          - init__monolith is false

    - name: Collection repository detected
      ansible.builtin.set_fact:
        init_project_type: collection
      when: init__collectionpath_stat.stat.exists is true

    - name: Monolith repository detected
      ansible.builtin.set_fact:
        init_project_type: monolith
      when:
        - init__monolith is true
        - init__rolepath_stat.stat.exists is false

- name: Autodetection succeeded
  ansible.builtin.assert:
    that:
      - init_project_type != 'auto'
    fail_msg: Autodetection of repository type failed!

- name: Repository type supported
  ansible.builtin.assert:
    that:
      - init_project_type != 'monolith'
    fail_msg: Monolith type repositories are not yet supported!

